name: neuralcode
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.16+27

environment:
  sdk: '>=3.2.2 <4.0.0'
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  http: ^1.1.0
  dio: ^5.4.1
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.4
  google_fonts: ^6.2.1
  pinput: ^5.0.0
  fluttertoast: ^8.2.5
  file_picker: ^8.1.4
  jwt_decoder: ^2.0.1
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.1.5
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  provider: ^6.1.1
  google_sign_in: ^6.2.1
  rxdart:
  flutter_screenutil: ^5.9.3
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  font_awesome_flutter:
  app_links: ^6.3.2
  in_app_update: ^4.2.3
  upgrader: ^11.3.0
  awesome_notifications: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/