name: neuralcode
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.4+12

environment:
  sdk: '>=3.2.2 <4.0.0'

# consider running `flutter pub upgrade --major-versions`. Alternatively,
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  http: ^1.1.0
  dio: ^5.4.1
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.4
  colorful_safe_area: ^1.0.0
  google_fonts: ^5.1.0
  pinput: ^2.2.31
  fluttertoast: ^8.2.5
  file_picker: ^6.1.1
  jwt_decoder: ^2.0.1
  sleek_circular_slider: ^2.0.1
  flutter_local_notifications: ^15.1.1
  firebase_messaging: ^14.6.8
  firebase_auth: ^4.16.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.0
  provider: ^6.1.1
  google_sign_in: ^6.2.1
  rxdart:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/